name: hotel_book
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  connectivity_plus: ^4.0.1
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  path_provider: ^2.1.3
  dartz: ^0.10.1
  flutter_riverpod: ^2.5.1
  json_serializable: ^6.8.0
  shared_preferences: ^2.2.3
  multi_select_flutter: ^4.1.3
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  awesome_dio_interceptor: ^1.2.0
  equatable: ^2.0.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  json_annotation: ^4.9.0
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.6
  mockito: ^5.4.4
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  integration_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/world.jpg
    - assets/images/chhimei.jpg
    - assets/images/horizon.jpg
