// Mocks generated by Mockito 5.4.4 from annotations
// in hotel_book/test/unit_test/auth_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i9;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i7;
import 'package:hotel_book/features/auth/domain/entity/user_entity.dart'
    as _i10;
import 'package:hotel_book/features/auth/domain/use_case/auth_use_case.dart'
    as _i2;
import 'package:hotel_book/features/auth/presentation/navigator/login_navigator.dart'
    as _i3;
import 'package:hotel_book/features/auth/presentation/navigator/register_navigator.dart'
    as _i4;
import 'package:hotel_book/features/auth/presentation/state/auth_state.dart'
    as _i5;
import 'package:hotel_book/features/auth/presentation/viewmodel/auth_view_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthUseCase_0 extends _i1.SmartFake implements _i2.AuthUseCase {
  _FakeAuthUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginViewNavigator_1 extends _i1.SmartFake
    implements _i3.LoginViewNavigator {
  _FakeLoginViewNavigator_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegisterNavigator_2 extends _i1.SmartFake
    implements _i4.RegisterNavigator {
  _FakeRegisterNavigator_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthState_3 extends _i1.SmartFake implements _i5.AuthState {
  _FakeAuthState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthViewModel extends _i1.Mock implements _i6.AuthViewModel {
  MockAuthViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthUseCase get authUseCase => (super.noSuchMethod(
        Invocation.getter(#authUseCase),
        returnValue: _FakeAuthUseCase_0(
          this,
          Invocation.getter(#authUseCase),
        ),
      ) as _i2.AuthUseCase);

  @override
  _i3.LoginViewNavigator get loginNavigator => (super.noSuchMethod(
        Invocation.getter(#loginNavigator),
        returnValue: _FakeLoginViewNavigator_1(
          this,
          Invocation.getter(#loginNavigator),
        ),
      ) as _i3.LoginViewNavigator);

  @override
  _i4.RegisterNavigator get signupNavigator => (super.noSuchMethod(
        Invocation.getter(#signupNavigator),
        returnValue: _FakeRegisterNavigator_2(
          this,
          Invocation.getter(#signupNavigator),
        ),
      ) as _i4.RegisterNavigator);

  @override
  set onError(_i7.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<_i5.AuthState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i8.Stream<_i5.AuthState>.empty(),
      ) as _i8.Stream<_i5.AuthState>);

  @override
  _i5.AuthState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAuthState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.AuthState);

  @override
  set state(_i5.AuthState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.AuthState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeAuthState_3(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i5.AuthState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> uploadImage(_i9.File? file) => (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [file],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> registerUser(_i10.UserEntity? user) => (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [user],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loginUser(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginUser,
          [
            email,
            password,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void openRegisterView() => super.noSuchMethod(
        Invocation.method(
          #openRegisterView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openLoginView() => super.noSuchMethod(
        Invocation.method(
          #openLoginView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openDashBoard() => super.noSuchMethod(
        Invocation.method(
          #openDashBoard,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i5.AuthState? old,
    _i5.AuthState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i7.RemoveListener addListener(
    _i11.Listener<_i5.AuthState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i7.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
